# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.9.0
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  #  profile: D:/ruoyi/uploadPath
  profile: uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.petlife.platform: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: dev # 默认使用开发环境，生产时改成 prod
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置检测空闲连接的间隔时间（单位毫秒）
      timeBetweenEvictionRunsMillis: 60000
      # 连接最小生存时间（单位毫秒）
      minEvictableIdleTimeMillis: 300000
      # 连接最大生存时间（单位毫秒）
      maxEvictableIdleTimeMillis: 900000
      # 校验连接有效性SQL
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.petlife.platform.**.domain
  # 配置mapper的扫描
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

# 防止XSS攻击dev
xss:
  # 过滤开关
  enabled: true
  # 排除链接
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 地图API配置（支持高德地图和天地图）
map:
  # 地图服务提供商：amap（高德）、tianditu（天地图）
  provider: tianditu
  # 请求超时时间（毫秒）
  timeout: 5000
  # 高德地图配置
  amap:
    # 高德地图API Key（请替换为您申请的真实Key）
    api-key: 6400f069a0114d30da1234f65063d8c9
    # 地理编码API地址
    geocoding-url: https://restapi.amap.com/v3/geocode/geo
    # 逆地理编码API地址
    regeo-url: https://restapi.amap.com/v3/geocode/regeo
  # 天地图配置
  tianditu:
    # 天地图API Key（请替换为您申请的真实Key）
    api-key: YOUR_TIANDITU_API_KEY_HERE
    # 地理编码API地址
    geocoding-url: http://api.tianditu.gov.cn/geocoder
    # 逆地理编码API地址
    regeo-url: http://api.tianditu.gov.cn/geocoder

# 短信服务配置
sms:
  # 禁用启动时的配置验证
  validation:
    enabled: false
  # 现有配置保持不变...
  provider: wangwei
  timeout: 10000
  # 验证码模板配置
  templates:
    # 登录验证码模板
    login-code:
      content: "code:{code}"
      expire-minutes: 5
  # 望为短信配置
  wangwei:
    host: https://wwsms.market.alicloudapi.com
    path: /send_sms
    app-code: fd4e6d2d32214e16a4b5e2bfe0857d86
    app-key: 204633337
    app-secret: jL82g8Q1N79SzKuMpP8dnLkIe7S0Kf7w
    template-id: wangweisms996
  # 三网106短信配置
  sanwang:
    host: https://gyytz.market.alicloudapi.com
    path: /sms/smsSend
    app-code: fd4e6d2d32214e16a4b5e2bfe0857d86
    app-key: 204633337
    app-secret: jL82g8Q1N79SzKuMpP8dnLkIe7S0Kf7w
    sms-sign-id: 2e65b1bb3d054466b82f0c9d125465e2
    template-id: 908e94ccf08b4476ba6c876d13f084ad
